import cors from "cors"
import express from "express"

const users = [
  {
      id: 1,
      title: "Red dead redemption",
      sub_title: "Red dead Redemption 2",
      genre: "Action", 
      rating: "PEGI 18",
      developer: "Rockstar Games",
      description: "America, 1899. Arthur Morgan e la banda di Van der Linde sono in fuga. Con gli agenti federali e i migliori cacciatori di taglie alle costole, la banda deve rapinare, combattere e rubare per farsi strada e cercare di sopravvivere nel cuore di un'America dura e selvaggia. Una serie di conflitti e divisioni rischiano di mettere a repentaglio l'unità del gruppo, e Arthur si ritrova costretto a scegliere tra i suoi ideali e la lealtà nei confronti della banda che l'ha cresciuto.", 
      price: 29.99,
      discount: 10,
      discount_price: 19.99,
      image_url: "https://image.api.playstation.com/cdn/UP1004/CUSA03041_00/Hpl5MtwQgOVF9vJqlfui6SDB5Jl4oBSq.png",
      video_url: "https://youtu.be/gmA6MrX81z4",
      platform: "Playstation",
  },
  {
      id: 2,
      title: "Mortal Kombat",
      sub_title: "Mortal Kombat 11 Ultimate",
      genre: "Fighting",
      rating: "PEGI 18",
      developer: "Warner Bros Games",
      description: "Una nuova storia a filmati che contribuirà al proseguimento dell'epica saga che va avanti da ormai 25 anni. I giocatori si caleranno nei panni di svariati personaggi di ieri e di oggi in una narrazione che sfida le leggi dello spazio-tempo mettendo Raiden contro Kronika, Custode del Tempo che ha dato vita a una realtà ambientata nell'alba dei tempi.", 
      price: 44.89,
      discount: 13,
      discount_price: 31.89,
      image_url: "https://gaming-cdn.com/images/products/8432/616x353/mortal-kombat-11-ultimate-ps4-ps5-ultimate-playstation-4-playstation-5-game-playstation-store-europe-cover.jpg?v=1701345153",
      video_url: "https://youtu.be/UoTams2yc0s",
      platform: "Playstation",
  },
  {
      id: 3,
      title: "God of War",
      sub_title: "God of War: Ragnarok",
      genre: "Adventure",
      rating: "PEGI 18",
      developer: "Santa Monica Studio",
      description: "Unisciti a Kratos e Atreus in un viaggio mitico alla ricerca di risposte prima che sopraggiunga il Ragnarök. Insieme, padre e figlio si spingeranno al limite nel corso del loro viaggio in ognuno dei nove regni.", 
      price: 47.99,
      discount: 20,
      discount_price: 27.99,
      image_url: "https://gaming-cdn.com/images/products/9312/616x353/god-of-war-ragnarok-ps5-playstation-5-game-playstation-store-europe-cover.jpg?v=1683626731",
      video_url:"https://youtu.be/ItyO3chi9bo",
      platform: "Playstation",
  },
  {
      id: 4,
      title: "Just dance",
      sub_title: "Just dance 2024 Edition",
      genre: "Multiplayer",
      rating: "PEGI 3",
      developer: "Ubisoft",
      description: "Balla e condividi momenti emozionanti per tutto l'anno con la piattaforma videoludica musicale più amata di tutti i tempi! Just Dance 2024 Edition include 40 brani tra hit recenti e grandi classici, come Flowers di Miley Cyrus, Tití Me Preguntó di Bad Bunny, How You Like That delle BLACKPINK e I Wanna Dance With Somebody di Whitney Houston!", 
      price: 23.99,
      discount: 5,
      discount_price: 18.99,
      image_url: "https://image.api.playstation.com/vulcan/ap/rnd/202310/0416/5c565008ffe01b5ee17799a0b76f5d1052fcb6aba1adab9e.jpg",
      video_url: "https://youtu.be/NniXc724TtU",
      platform: "Playstation",
  },
  {
      id: 5,
      title: "Horizion",
      sub_title: "Horizon: Forbidden West",
      genre: "Adventure",
      rating: "PEGI 16",
      developer: "Guerrilla Games",
      description: "Unisciti ad Aloy nell'esplorazione dell'Ovest Proibito, una pericolosa frontiera che nasconde nuove e misteriose minacce.", 
      price: 36.42,
      discount: 12,
      discount_price: 24.99,
      image_url: "https://image.api.playstation.com/vulcan/ap/rnd/202107/3100/cb7gh5N3DjSRathadczu40S9.png",
      video_url: "https://youtu.be/Lq594XmpPBg",
      platform: "Playstation",
  },
  {
      id: 6,
      title: "Medieval Dinasty",
      sub_title: "Medieval Dinasty",
      genre: "FPS",
      rating: "PEGI 16",
      developer: "Render Cube",
      description: "Trova un terreno su cui costruire la tua dimora. Inizierai da semplice agricoltore o cacciatore, ma man mano che acquisirai più esperienza, apprenderai nuove abilità e le affinerai, diventerai il capo di una fiorente cittadina. Progetta, costruisci e migliora la tua casa: trasforma una semplice capanna in una vasta fattoria. Convinci le persone a unirsi al tuo villaggio. Trova il vero amore e metti su famiglia per garantire una continuità nella tua dinastia.", 
      price: 23.99,
      discount: 6,
      discount_price: 17.99,
      image_url: "https://image.api.playstation.com/vulcan/ap/rnd/202308/1609/9ef2acb3ed2cda2a894342473bd82fda34e73b3a35f57aef.jpg",
      video_url: "https://youtu.be/0m_XJdDvcf4",
      platform: "Playstation",
  },
  {
      id: 7,
      title: "Uncharted",
      sub_title: "Uncharted: Legacy of Thieves",
      genre: "Adventure",
      rating: "PEGI 16",
      developer: "Naughty Dog",
      description: "Scopri le imprese del passato con i ladri Nathan Drake e Chloe Frazer, personaggi tanto carismatici quanto complessi, mentre viaggiano per il mondo in cerca di avventure e storie straordinarie, ora rimasterizzate magistralmente per la console PS5™ con grafica e framerate migliorati.", 
      price: 44.99,
      discount: 6,
      discount_price: 34.89,
      image_url: "https://image.api.playstation.com/vulcan/ap/rnd/202111/2000/gTUWTlvPHzxFJ2JAxtDyI2eS.png",
      video_url: "https://youtu.be/F3Wl-OiZCO4",
      platform: "Playstation",
  },
  {
      id: 8,
      title: "Assassin's creed",
      sub_title: "Assassin's creed: Mirage",
      genre: "Action",
      rating: "PEGI 18",
      developer: "Ubisoft",
      description: "Indossa i panni di Basim, un astuto ladruncolo da strada che cerca risposte e giustizia nelle affollate vie della Bagdad del IX secolo. Grazie a un'antica e misteriosa organizzazione nota come gli Occulti, diventerà un letale Maestro Assassino e cambierà il suo destino in modi imprevedibili.", 
      price: 59.99,
      discount: 20,
      discount_price: 39.99,
      image_url: "https://gaming-cdn.com/images/products/9187/616x353/assassin-s-creed-mirage-pc-game-ubisoft-connect-europe-cover.jpg?v=1696577233",
      video_url: "https://youtu.be/lirm6x2AJVc",
      platform: "Playstation",
  },
  {
      id: 9,
      title: "FC 24",
      sub_title: "FC 24",
      genre: "sport",
      rating: "PEGI 3",
      developer: "Electronic Arts",
      description: "Un gioco di calcio", 
      price: 33.99,
      discount: 8,
      discount_price: 25.99,
      image_url: "https://cdn1.epicgames.com/offer/4750c68b2bfa4f43933b81cfd5cc510c/EGS_EASPORTSFC24StandardEdition_EACanada_S1_2560x1440-f1772618b782ca975f0bbe33db3a88b3",
      video_url: "https://youtu.be/XhP3Xh4LMA8",
      platform: "Playstation",
  },
  {
      id: 10,
      title: "Ratchet & Clank",
      sub_title: "Ratchet & Clanck: Rift Apart",
      genre: "Adventure",
      rating: "PEGI 3",
      developer: "Imsomniac Games",
      description: "Ratchet e Clank sono tornati! Aiutali a impedire che un imperatore robot riesca a sottomettere i mondi interdimensionali, a partire dal loro universo. Il duo potrà contare sull'aiuto di Rivet, una ribelle Lombax proveniente da un'altra realtà.", 
      price: 35.99,
      discount: 10,
      discount_price: 25.99,
      image_url: "https://image.api.playstation.com/vulcan/ap/rnd/202101/2921/DwVjpbKOsFOyPdNzmSTSWuxG.png",
      video_url: "https://youtu.be/ai3o0XtrnM8",
      platform: "Playstation",
  },
  {
      id: 11,
      title: "Dragon's Dogma",
      sub_title: "Dragon's Dogma 2",
      genre: "Adventure",
      rating: "PEGI 16",
      developer: "Capcom",
      description: "Dragon's Dogma è una serie di GDR per giocatore singolo ricca di azione e narrazione che offre ai giocatori la possibilità di scrivere la propria storia, dall'aspetto del loro Arisen, la sua classe, la sua squadra, l'approccio alle varie situazioni e molto altro. Ora, in questo attesissimo sequel, il vasto ed esplorabile mondo fantasy di Dragon's Dogma 2 ti attende.", 
      price: 49.99,
      discount: 9,
      discount_price: 40.99,
      image_url: "https://gaming-cdn.com/images/products/7911/616x353/dragon-s-dogma-2-pc-game-steam-europe-cover.jpg?v=1711626178",
      video_url: "https://youtu.be/cT0rIgaiPWA",
      platform: "XBOX",
  },
  {
      id: 12,
      title: "Avatar",
      sub_title: "Avatar: Frontiers of Pandora",
      genre: "Adventure",
      rating: "PEGI 12",
      developer: "Ubisoft",
      description: "Avatar: Frontiers of Pandora™ è un gioco d'azione-avventura in prima persona ambientato nell'inesplorata frontiera occidentale di Pandora. Dopo il tuo rapimento e addestramento a opera della corporazione militare umana nota come RDA, hai dimenticato la tua origine na'vi e hai vissuto per servire la sua causa. Quindici anni più tardi hai riconquistato la libertà, ma la tua stessa casa ti risulta straniera. Scopri la tua eredità perduta e cosa significa essere na'vi e lotta al fianco degli altri clan per proteggere Pandora dall'RDA.", 
      price: 34.99,
      discount: 8,
      disocunt_price: 24.99,
      image_url: "https://gaming-cdn.com/images/products/9014/616x353/avatar-frontiers-of-pandora-pc-game-ubisoft-connect-europe-cover.jpg?v=1702461541",
      video_url: "https://youtu.be/G-1evpoTzWU",
      platform: "XBOX",
  },
  {
      id: 13,
      title: "Halo",
      sub_title: "Halo: Infinite Campaign",
      genre: "FPS",
      rating: "PEGI 16",
      developer: "343 Industries",
      description: "Quando ogni speranza sembra perduta e il destino dell'umanità è appeso a un filo, Master Chief si trova ad affrontare il nemico più spietato di sempre. Indossa la corazza del più grande eroe dell'umanità ed esplora l'Halo in tutta la sua estensione in un'epica avventura open world.", 
      price: 23.99,
      discount: 4,
      discount_price: 19.99,
      image_url: "https://assets.xboxservices.com/assets/34/84/348495df-d8f9-43f4-94cf-12d6e641d610.jpg?n=Halo-Infinite_Poster-Image_1920x1080.jpg",
      video_url: "https://youtu.be/PyMlV5_HRWk",
      platform: "XBOX",
  },
  {
      id: 14,
      title: "Starfield",
      sub_title: "Starfield",
      genre: "FPS",
      rating: "PEGI 16",
      developer: "Bethesda",
      description: "Nell'anno 2330, l'umanità si è avventurata oltre il sistema solare, si è insediata in nuovi pianeti ed è ormai una specie interstellare. In questo contesto ti unirai a Constellation, l'ultimo gruppo di esploratori spaziali alla ricerca di rari manufatti sparsi per la galassia, attraversando enormi distanze nel più grande e ambizioso gioco di Bethesda Game Studios di sempre.", 
      price: 55.89,
      discount: 15,
      discount_price: 40.89,
      image_url: "https://gaming-cdn.com/images/products/2675/616x353/starfield-pc-game-steam-cover.jpg?v=1708361145",
      video_url: "https://youtu.be/pYqyVpCV-3c",
      platform: "XBOX",
  },
  {
      id: 15,
      title: "Elden Ring",
      sub_title: "Elden Ring",
      genre: "Action",
      rating: "PEGI 18",
      developer: "FromSoftware",
      description: "Un mondo sconfinato e sorprendente. Un vasto mondo, in cui lande sconfinate e dense di pericoli si intersecano senza soluzione di continuità a dedali sotterranei dalle sontuose architetture tridimensionali. Esplora l'ignoto e combatti minacce mortali in un mondo in cui la sopravvivenza è una conquista.", 
      price: 37.99,
      discount: 4,
      discount_price: 33.99,
      image_url: "https://image.api.playstation.com/vulcan/ap/rnd/202107/1612/Y5RHNmzAtc6sRYwZlYiKHAxN.png",
      video_url: "https://youtu.be/AKXiKBnzpBQ",
      platform: "XBOX",
  },
  {
      id: 16,
      title: "Dragon Ball Z",
      sub_title: "Dragon Ball Z: Kakarot",
      genre: "Action",
      rating: "PEGI 12",
      developer: "Bandai Namco",
      description: "Ripercorri la storia di Goku e dei guerrieri Z in DRAGON BALL Z: KAKAROT! Oltre rivivere battaglie memorabili, potrai esplorare il mondo di DRAGON BALL Z cacciando, pescando, mangiando e allenandoti con Goku, Gohan, Vegeta e gli altri.", 
      price: 24.99,
      discount: 7,
      discount_price: 17.99,
      image_url: "https://image.api.playstation.com/vulcan/ap/rnd/202212/1616/ebKSYAneFeVLHD7SAWP1l5TE.png",
      video_url: "https://youtu.be/sixbriRUz9M",
      platform: "XBOX",
  },
  {
      id: 17,
      title: "It takes two",
      sub_title: "It takes two",
      genre: "Indie",
      rating: "PEGI 3",
      developer: "Electronic Arts",
      description: "Parti per la più folle avventura della tua vita con It Takes Two, un'avventura platform che rivoluziona il genere, creata appositamente per il co-op. Invita un amico a giocare gratis con il Pass amici*, collaborate per superare numerose sfide incredibili con un gameplay fuori dagli schemi. Gioca nei panni di Cody e May, una coppia ai ferri corti, due esseri umani che un incantesimo ha trasformato in bambole. Insieme, intrappolati in un mondo fantastico in cui gli imprevisti si celano dietro ogni angolo, dovranno superare ogni sfida per salvare la propria relazione in pericolo.", 
      price: 19.99,
      discount: 10,
      discount_price: 9.99,
      image_url: "https://image.api.playstation.com/vulcan/ap/rnd/202012/0815/7CRynuLSAb0vysSC4TmZy5e4.png",
      video_url: "https://youtu.be/GAWHzGNcTEw",
      platform: "XBOX",
  },
  {
      id: 18,
      title: "Forza Horizion",
      sub_title: "Forza Horizon 5",
      genre: "Racing",
      rating: "PEGI 3",
      developer: "Playground Games",
      description: "La tua avventura Horizon definitiva ti aspetta! Esplora vivaci paesaggi open world del Messico in continua evoluzione. Divertimento al volante illimitato con centinaia tra le migliori auto al mondo.", 
      price: 50.99,
      discount: 14,
      discount_price: 36.99,
      image_url: "https://gaming-cdn.com/images/products/8701/616x353/forza-horizon-5-pc-xbox-one-xbox-series-x-s-pc-xbox-one-xbox-series-x-s-game-microsoft-store-cover.jpg?v=1705510676",
      video_url: "https://youtu.be/FYH9n37B7Yw",
      platform: "XBOX",
  },
  {
      id: 19,
      title: "Like a Dragon: Infinite Wealth",
      sub_title: "Like a Dragon: Infinite Wealth",
      genre: "Fighting",
      rating: "PEGI 18",
      developer: "Ryu ga Gotoku Studio",
      description: "Goditi un combattimento unico nel suo genere con battaglie GDR dinamiche e frenetiche in cui il campo di battaglia stesso diventa la tua arma e non ci sono regole.Adatta le tecniche del tuo gruppo alla situazione da affrontare con lavori e personalizzazioni bizzarri per sopraffare strategicamente i nemici con tecniche sopra le righe.", 
      price: 44.99,
      discount: 15,
      discount_price: 29.99,
      image_url: "https://image.api.playstation.com/vulcan/ap/rnd/202007/0917/fid2e7IysrUvFqmppIxi48GT.png",
      video_url: "https://youtu.be/ZcYdoEju54c",
      platform: "XBOX",
  },
  {
      id: 20,
      title: "Assassin's creed",
      sub_title: "Assassin's creed: Ezio's Collection",
      genre: "Adventure",
      rating: "PEGI 18",
      developer: "Ubisoft",
      description:"Scrivi la storia nei panni del Maestro Assassino Ezio Auditore da Firenze in questa magnifica collezione che comprende la modalità per giocatore singolo di Assassin's Creed 2, Assassin's Creed Brotherhood, Assassin's Creed Revelations e tutti i DLC con grafica migliorata. Due brevi film, Assassin's Creed Lineage® e Assassin's Creed Embers™, completano l'esperienza di Ezio.", 
      price: 17.99,
      discount: 3,
      discount_price: 14.99,
      image_url: "https://image.api.playstation.com/cdn/EP0001/CUSA04893_00/Du24dEL6C7seAl3UQobFN5QqewZ6EXU5.png",
      video_url: "https://youtu.be/PrlE5PmeasA",
      platform: "XBOX",
  },
  {
      id: 21,
      title: "Disney Dreamlight Valley",
      sub_title: "Disney Dreamlight Valley",
      genre: "Adventure",
      rating: "PEGI 3",
      developer: "Disney",
      description:"Disney Dreamlight Valley è un gioco ibrido che unisce avventura e simulazione sociale, con una miriade di missioni, esplorazioni e attività coinvolgenti al fianco di amici Disney e Pixar vecchi e nuovi. Un tempo, la Dreamlight Valley era un luogo pacifico in cui i personaggi Disney e Pixar vivevano in armonia. Un giorno, però, è giunto l’Oblio, che ha fatto crescere in tutta la valle le Spine della notte e ha fatto svanire gli splendidi ricordi legati a questo luogo magico. Non avendo altri posti in cui andare, i disperati abitanti della Dreamlight Valley si sono rinchiusi nel Castello dei sogni.", 
      price: 39.99,
      discount: 10,
      discount_price: 29.99,
      image_url: "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_download_software_1/2x1_NSwitchDS_DisneyDreamlightValley_LionKing_image1600w.jpg",
      video_url: "https://youtu.be/UY5KdtnK4dU",
      platform: "Nintendo",
  },
  {
    id: 22,
    title: "Moonlighter",
    sub_title: "Moonlighter",
    genre: "Indie",
    rating: "PEGI 7",
    developer: "Digital Sun",
    description:"Tanto tempo fa, nel corso di alcuni scavi archeologici, fu portata alla luce una serie di varchi. Ben presto la gente si rese conto che questi antichi varchi conducevano ad altri regni e nuove dimensioni. Vicino al sito archeologico fu fondato un piccolo villaggio dedito al commercio, chiamato Rynoka, che permetteva a coraggiosi e spericolati esploratori di entrare in possesso di tesori inestimabili.", 
    price: 24.99,
    discount: 22,
    discount_price: 2.99,
    image_url: "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_Moonlighter_image1600w.jpg",
    video_url: "https://youtu.be/Hp7tNAH9Ox0",
    platform: "Nintendo",
},
{
  id: 23,
  title: "Goat Simulator",
  sub_title: "Goat Simulator: The GOATY",
  genre: "Indie",
  rating: "PEGI 12",
  developer: "Coffe stain",
  description:"Come sarà la vita di una capra? Beh, grazie a Goat Simulator adesso puoi avere la risposta a una domanda che ti assillava da sempre! In Goat Simulator vesti i panni di una capra che deve seminare la distruzione più grande possibile. Questo gioco è stato paragonato ai titoli di skateboard vecchia scuola, solo che invece di essere uno skater sei una capra, e invece di eseguire acrobazie fracassi tutto ciò che ti capita a tiro. Facendolo con stile guadagnerai anche più punti!", 
  price: 29.99,
  discount: 25,
  discount_price: 4.99,
  image_url: "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_download_software_1/H2x1_NSwitchDS_GoatSimulatorTheGoaty_image1600w.jpg",
  video_url: "https://youtu.be/SRc9jIO1mCI",
  platform: "Nintendo",
},
{
  id: 24,
  title: "Animal Crossing",
  sub_title: "Animal Crossing New Horizon",
  genre: "Multiplayer",
  rating: "PEGI 3",
  developer: "Nintendo",
  description:"Una vita spensierata è all'orizzonte! Scendi dall'aereo sulla tua personale isola deserta dove nuove amicizie, scoperte e opportunità ti attendono. Crea il tuo paradiso in Animal Crossing: New Horizons per Nintendo Switch!", 
  price: 59.99,
  discount: 20,
  discount_price: 39.99,
  image_url: "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_AnimalCrossingNewHorizons_image1600w.jpg",
  video_url: "https://youtu.be/_3YNL0OWio0",
  platform: "Nintendo",
},
{
  id: 25,
  title: "Hogwarts Legacy",
  sub_title: "Hogwarts Legacy",
  genre: "RPG",
  rating: "PEGI 12",
  developer: "Avalanche Software",
  description:"Hogwarts Legacy è un coinvolgente gioco di ruolo d'azione open world, ambientato nel magico universo dei libri di Harry Potter. Ora puoi assumere il controllo della narrazione ed essere il protagonista della tua storia personale nel mondo magico.", 
  price: 59.99,
  discount: 25,
  discount_price: 34.99,
  image_url: "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/2x1_NSwitch_HogwartsLegacy_image1600w.jpg",
  video_url: "https://youtu.be/KOZpJB1FK6Y",
  platform: "Nintendo",
},
{
  id: 26,
  title: "The Elder Scrolls",
  sub_title: "The Elder Scrolls V: Skyrim",
  genre: "RPG",
  rating: "PEGI 18",
  developer: "Bethesda",
  description:"Quest'avventura open world dei Bethesda Game Studios® in cui puoi essere chi vuoi e fare ciò che desideri ti permette ora di giocare ovunque: sulla TV di casa o in mobilità. The Elder Scrolls V: Skyrim per Nintendo Switch include funzionalità esclusive, come la possibilità di usare i comandi di movimento per combattere e scassinare serrature, nuovi costumi ed equipaggiamento dalla serie di The Legend of Zelda e la compatibilità con gli amiibo (venduti separatamente).", 
  price: 59.99,
  discount: 30,
  discount_price: 29.99,
  image_url: "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_TheElderScrollsVSkyrim_image1600w.jpg",
  video_url: "https://youtu.be/fx0eznPrKpw",
  platform: "Nintendo",
},
{
  id: 27,
  title: "The Survivalist",
  sub_title: "The Survivalist",
  genre: "RPG",
  rating: "PEGI 7",
  developer: "Team17 Digital Ltd",
  description:"Caccia gli animali, a tuo rischio e pericolo, e incontra una serie di creature leggendarie... anche se non tutte potrebbero essere liete di vederti. Ricevi gli incarichi da un misterioso straniero oppure scoprili da solo tra le sabbie dell'isola. Preparati a inoltrarti in uno scenario generato proceduralmente con una varietà estrema di biomi, per un'avventura sempre nuova e diversa a ogni partita.", 
  price: 24.99,
  discount: 22,
  discount_price: 2.99,
  image_url: "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_TheSurvivalists_image1600w.jpg",
  video_url: "https://youtu.be/YsEmt5qKvVk",
  platform: "Nintendo",
},
{
  id: 28,
  title: "Football Manager",
  sub_title: "Football Manager 2024 Touch",
  genre: "Simulation",
  rating: "PEGI 3",
  developer: "SEGA",
  description:"Scrivi la tua storia. Insegui la gloria immediata alla guida di uno dei principali top club al mondo o sfrutta la nuova compatibilità con i salvataggi precedenti per proseguire il tuo viaggio da FM23 Touch. A te la scelta.", 
  price: 49.99,
  discount: 16,
  discount_price: 33.99,
  image_url: "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_download_software_1/2x1_NSwitchDS_FootballManager2024Touch_image1600w.jpg",
  video_url: "https://youtu.be/YhW8wxAD4H0",
  platform: "Nintendo",
},
{
  id: 29,
  title: "Two Points Hospital",
  sub_title: "Two Points Hospital: Jumbo Edition",
  genre: "Simulation",
  rating: "PEGI 3",
  developer: "Two Points Studios",
  description:"Unisciti a oltre 3 milioni di giocatori felici e scopri perché Two Point Hospital è un sano fenomeno! Accresci la tua esperienza di costruttore di ospedali con le quattro enormi espansioni e i due DLC aggiuntivi compresi nella straordinaria Jumbo Edition del gioco, STRABORDANTE DI CONTENUTI!", 
  price: 39.99,
  discount: 34,
  discount_price: 5.99,
  image_url: "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_TwoPointHospital_image1600w.jpg",
  video_url: "https://youtu.be/zt7KXD-QPpE",
  platform: "Nintendo",
},
{
  id: 30,
  title: "Doraemon",
  sub_title: "Doraemon Story of Seasons",
  genre: "Simulation",
  rating: "PEGI 3",
  developer: "Bandai Namco",
  description:"Dopo essere stati colti di sorpresa da una tempesta, Nobita, il nostro eroe, atterra accidentalmente su un pianeta insieme ai suoi amici. Lì incontrano gli abitanti locali, i quali raccontano che la tempesta ha spazzato via tutto tranne un albero speciale. Nobita e i suoi amici decidono allora di aiutare il villaggio a tornare alla prosperità, in cambio gli abitanti del villaggio aiuteranno loro a far ritorno sulla terra.", 
  price: 49.99,
  discount: 42,
  discount_price: 7.99,
  image_url: "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_DoraemonStoryOfSeasons_image1600w.jpg",
  video_url: "https://youtu.be/YuKO0tUVoQI",
  platform: "Nintendo",
},
{
  id: 31,
  title: "Farming Simulator",
  sub_title: "Farming Simulator 22",
  genre: "Simulation",
  rating: "PEGI 3",
  developer: "Coffe Stain",
  description:"Farming Simulator Premium Edition for PC is a farming simulation game in which you can build your own farm to grow an agricultural empire. You can choose everything from the crops you grow to how much automation you want to invest in.", 
  price: 39.99,
  discount: 23,
  discount_price: 26.99,
  image_url: "https://gaming-cdn.com/images/products/14538/616x353/farming-simulator-22-premium-edition-premium-edition-pc-mac-game-steam-cover.jpg?v=1711362759",
  video_url: "https://youtu.be/JpBzfTe_yWE",
  platform: "PC",
},
{
  id: 32,
  title: "Elden Ring",
  sub_title: "Elden Ring: Shadow of the Erdtree",
  genre: "Action",
  rating: "PEGI 18",
  developer: "Bandai Namco",
  description:"Winner of hundreds of accolades including The Game Awards Game of the Year and Golden Joystick Awards Ultimate Game of the Year, ELDEN RING is the acclaimed action RPG epic set in a vast, dark fantasy world.", 
  price: 49.99,
  discount: 11,
  discount_price: 38.99,
  image_url: "https://gaming-cdn.com/images/products/13652/616x353/elden-ring-shadow-of-the-erdtree-pc-game-steam-europe-cover.jpg?v=1709640799",
  video_url: "https://youtu.be/qLZenOn7WUo",
  platform: "PC",
},
{
  id: 33,
  title: "Total War",
  sub_title: "Total War: Pharaoh",
  genre: "Simulation",
  rating: "PEGI 18",
  developer: "SEGA",
  description:"In Total War: PHARAOH immerse yourself in ancient Egypt at the zenith of its power and experience the dramatic events that threaten its destruction. With dynamic real-time battles and incredible turn-based empire management, will you rise to become Egypt's last great Pharaoh, or a conquering Great King of the Hittites? ", 
  price: 39.99,
  discount: 32,
  discount_price: 7.99,
  image_url: "https://gaming-cdn.com/images/products/14196/616x353/total-war-pharaoh-pc-mac-game-steam-cover.jpg?v=1702639864",
  video_url: "https://youtu.be/lLlD650ZBFQ",
  platform: "PC",
},
{
  id: 34,
  title: "Smalland",
  sub_title: "Smalland",
  genre: "Adventure",
  rating: "PEGI 7",
  developer: "Merge Games",
  description:"Traverse lake sized puddles, scale skyscraper sized trees, scramble through cavernous cracks in roads, as you experience a huge open world from a new perspective. Explore dense forests, hazardous swamps and strange ruins left over from the time before. Uncover lore and knowledge from hidden NPCs scattered throughout the world and learn to survive in this vast wilderness.", 
  price: 34.99,
  discount: 16,
  discount_price: 18.99,
  image_url: "https://gaming-cdn.com/images/products/8256/616x353/smalland-survive-the-wilds-pc-game-steam-cover.jpg?v=1708684863",
  video_url: "https://youtu.be/n9EvL-I91TA",
  platform: "PC",
},
{
  id: 35,
  title: "Alone in the dark",
  sub_title: "Alone in the dark",
  genre: "Adventure",
  rating: "PEGI 12",
  developer: "Pieces Interactive",
  description:"We invite you to join us on a journey into madness, where each encounter could be your last. With each step you take closer to unravelling Derceto's mystery, the eyes that watch from the darkness grow hungrier.", 
  price: 59.99,
  discount: 24,
  discount_price: 35.99,
  image_url: "https://gaming-cdn.com/images/products/12675/616x353/alone-in-the-dark-pc-game-steam-europe-cover.jpg?v=1710947479",
  video_url: "https://youtu.be/ddsa1IB9MH4",
  platform: "PC",
},
{
  id: 36,
  title: "RoboCop",
  sub_title: "RoboCop: Rogue City",
  genre: "Action",
  rating: "PEGI 12",
  developer: "Teyon",
  description:"RoboCop: Rogue City for PC is a first-person shooter game that slots in between the events of the films RoboCop 2 and Robocop 3. Anne Lewis returns as RoboCop's partner and is always with you as you play, making a useful sidekick.", 
  price:49.99,
  discount: 30,
  discount_price: 19.99,
  image_url: "https://gaming-cdn.com/images/products/9229/616x353/robocop-rogue-city-pc-game-steam-cover.jpg?v=1701276307",
  video_url: "https://youtu.be/2VS00ILM2TY",
  platform: "PC",
},
{
  id: 37,
  title: "Ghost of Tsushima",
  sub_title: "Ghost of Tsushima: Director's cut",
  genre: "Adventure",
  rating: "PEGI 18",
  developer: "Sucker Punch Production",
  description:"Ghost of Tsushima for PC is an award winning action adventure open world game, with a third-person player perspective. It is set in ancient feudal Japan, but the issues faced by the protagonist will be easily understood by Western, modern players. About", 
  price: 59.99,
  discount: 10,
  discount_price: 49.99,
  image_url: "https://gaming-cdn.com/images/products/9093/616x353/ghost-of-tsushima-director-s-cut-pc-game-steam-cover.jpg?v=1711457077",
  video_url: "https://youtu.be/A5gVt028Hww",
  platform: "PC",
},
{
  id: 38,
  title: "Final Fantasy ",
  sub_title: "Final Fantasy XIV: Dawntrail",
  genre: "RPG",
  rating: "PEGI 12",
  developer: "Square Enix",
  description:"Blue seas, clear skies, and boundless possibilities await in Dawntrail, the newest expansion pack for the critically acclaimed FINAL FANTASY XIV Online! Explore uncharted territories with familiar faces as you discover new tribes, confront formidable threats, and expand your horizons as hope's light dawns once more.", 
  price: 35.99,
  discount: 11,
  discount_price: 24.99,
  image_url: "https://gaming-cdn.com/images/products/15658/616x353/final-fantasy-xiv-dawntrail-early-access-pc-game-europe-cover.jpg?v=1711621232",
  video_url: "https://youtu.be/kgiuQwzB6aU",
  platform: "PC",
},
{
  id: 39,
  title: "Helldivers",
  sub_title: "Helldivers II",
  genre: "FPS",
  rating: "PEGI 18",
  developer: "Arrowhead Game Studio",
  description:"The Galaxy's Last Line of Offence. Enlist in the Helldivers and join the fight for freedom across a hostile galaxy in a fast, frantic, and ferocious third-person shooter. URGENT BROADCAST SUPER EARTH ARMED FORCESFreedom.", 
  price: 39.99,
  discount: 15,
  discount_price: 24.99,
  image_url: "https://gaming-cdn.com/images/products/9575/616x353/helldivers-2-pc-game-steam-europe-cover.jpg?v=1708503564",
  video_url: "https://youtu.be/Dhd9FYLLEPc",
  platform: "PC",
},
{
  id: 40,
  title: "Conan Exiles",
  sub_title: "Conan Exiles",
  genre: "RPG",
  rating: "PEGI 18",
  developer: "Funcom",
  description:"Un survival multigiocatore online, ora con la magia, ambientato nelle terre di Conan il Barbaro. Sopravvivi in un enorme mondo sandbox, crea un regno partendo da una semplice casa e annienta i nemici in modalità giocatore singolo o multigiocatore.", 
  price: 24.99,
  discount: 20,
  discount_price: 4.99,
  image_url: "https://gaming-cdn.com/images/products/1258/orig/conan-exiles-pc-gioco-steam-cover.jpg?v=1683883216",
  video_url: "https://youtu.be/73oUz5psOGE",
  platform: "PC",
},
{
  id: 41,
  title: "Assassin's creed",
  sub_title: "Assassin's creed: Valhalla",
  genre: "Adventure",
  rating: "PEGI 18",
  developer: "Ubisoft",
  description:"Diventa una leggenda tra i vichinghi, scrivi il tuo nome nella Storia. Compi razzie contro i tuoi nemici, espandi il tuo insediamento.", 
  price: 44.99,
  discount: 25,
  discount_price: 19.99,
  image_url: "https://cdn1.epicgames.com/400347196e674de89c23cc2a7f2121db/offer/AC%20KINGDOM%20PREORDER_STANDARD%20EDITION_EPIC_Key_Art_Portrait_640x854-640x854-288120c5573756cb988b6c1968cebd86.png",
  video_url: "https://youtu.be/h0A0K9VmaNA",
  platform: "Playstation",
},
{
  id: 42,
  title: "Cuphead",
  sub_title: "Cuphead",
  genre: "Indie",
  rating: "PEGI 12",
  developer: "Studio MDHR Enterteinment Inc.",
  description:"Cuphead è un classico action 'run and gun' fortemente incentrato sulle battaglie contro i boss. Ispirato ai cartoni animati degli anni '30, può vantare grafiche ed effetti audio accuratamente ricreati con le tecniche di quell'epoca (animazione tradizionale a mano, sfondi ad acquerello e registrazioni jazz", 
  price: 14.99,
  discount: 10,
  discount_price: 4.99,
  image_url: "https://cdn1.epicgames.com/400347196e674de89c23cc2a7f2121db/offer/AC%20KINGDOM%20PREORDER_STANDARD%20EDITION_EPIC_Key_Art_Portrait_640x854-640x854-288120c5573756cb988b6c1968cebd86.png",
  video_url: "https://cdn.cloudflare.steamstatic.com/steam/apps/256705156/movie480.webm?t=1515128214",
  platform: "PC",
},
{
  id: 43,
  title: "Mario Kart 8",
  sub_title: "Mario Kart 8 Deluxe",
  genre: "Racing",
  rating: "PEGI 3",
  developer: "Nintendo",
  description:"Vuoi sfidare la tua famiglia sullo schermo della TV, giocare all'aria aperta al parco o andare a casa di un amico? Nessun problema! Con Nintendo Switch puoi giocare a Mario Kart come preferisci!", 
  price: 49.99,
  discount: 20,
  discount_price: 29.99,
  image_url: "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_MarioKart8Deluxe_image1600w.jpg",
  video_url: "https://youtu.be/Y7v99bXtiz0",
  platform: "Nintendo",
},
{
  id: 44,
  title: "Mario vs Donkey Kong",
  sub_title: "Mario vs Donkey Kong",
  genre: "Action",
  rating: "PEGI 3",
  developer: "Nintendo",
  description:"I giocattoli sono di nuovo il pomo della discordia in Mario vs. Donkey Kong per Nintendo Switch! Supera enigmi e piattaforme nella tua missione per recuperare i Minimario rubati. Questo remake di un classico per Game Boy Advance include una grafica completamente aggiornata, livelli inediti e nuove modalità di gioco.", 
  price: 49.99,
  discount: 15,
  discount_price: 34.99,
  image_url: "https://assets.nintendo.com/image/upload/ar_16:9,c_lpad,w_1240/b_white/f_auto/q_auto/ncom/software/switch/70010000072191/2fda60f3007987817be456876e7755f5120522a75e477961fbb622fd32f9e588",
  video_url: "https://youtu.be/vY9tbE-2q0Y",
  platform: "Nintendo",
},
{
  id: 45,
  title: "Princess Peach Showtime",
  sub_title: "Princess Peach Showtime",
  genre: "Adventure",
  rating: "PEGI 3",
  developer: "Nintendo",
  description:"Un misterioso nemico mascherato ha preso il controllo del Teatro Splendente, e adesso solo la Principessa Peach può salvare lo spettacolo! Calati nel ruolo della protagonista e sfodera un intero guardaroba di trasformazioni in Princess Peach: Showtime! per Nintendo Switch.", 
  price: 59.99,
  discount: 20,
  discount_price: 39.99,
  image_url: "https://www.nintendo.com/eu/media/images/08_content_images/games_6/nintendo_switch_7/nswitch_princesspeachshowtime/PrincessPeachShowtime_TryIt_SQImage.jpg",
  video_url: "https://youtu.be/rp4CGMbKQwU",
  platform: "Nintendo",
},
{
  id: 46,
  title: "Prince of Persia",
  sub_title: "Prince of Persia: The Lost Crown",
  genre: "Adventure",
  rating: "PEGI 12",
  developer: "Ubisoft",
  description:"Tuffati in un entusiasmante e affascinante platform d'azione e avventura ambientato in una versione mitologica dell'antica Persia, dove potrai manipolare i confini del tempo e dello spazio. Vesti i panni dell'abile spadaccino Sargon e cresci fino a diventare una leggenda padroneggiando il combattimento acrobatico e sbloccando progressivamente nuovi poteri temporali e super abilità speciali.", 
  price: 59.99,
  discount: 20,
  discount_price: 39.99,
  image_url: "https://www.nintendo.com/eu/media/images/10_share_images/games_15/nintendo_switch_4/2x1_NSwitch_PrinceOfPersiaTheLostCrown_image1600w.jpg",
  video_url: "https://youtu.be/I-ra1bksSzs",
  platform: "Nintendo",
},
{
  id: 47,
  title: "Unicorn Overlord",
  sub_title: "Unicorn Overlord",
  genre: "RPG",
  rating: "PEGI 12",
  developer: "SEGA",
  description:"Dalle menti geniali che hanno dato vita a 13 Sentinels: Aegis Rim e Odin Sphere, la rinascita del GdR fantasy tattico secondo ATLUS x Vanillaware. Combatti contro il destino e parti per un'avventura per riconquistare il regno insieme ai tuoi fedeli alleati.", 
  price: 59.99,
  discount: 40,
  discount_price: 19.99,
  image_url: "https://fs-prod-cdn.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_5/1x1_NSwitch_UnicornOverlord_image500w.jpg",
  video_url: "https://youtu.be/_3l5cRRZyWE",
  platform: "Nintendo",
},
{
  id: 48,
  title: "Super Mario RPG",
  sub_title: "Super Mario RPG",
  genre: "RPG",
  rating: "PEGI 3",
  developer: "Nintendo",
  description:"Raduna un gruppo di eroi improbabili e imbarcati in una bizzarra avventura per riparare la Via Stellare, in grado di esaudire i desideri, in Super Mario RPG per Nintendo Switch, ora localizzato in italiano! Ferma la losca Banda di Fabbro Magno e incontra un mirabolante cast di personaggi straordinari, inclusi il misterioso pupazzo Geno e il tenero Mallow.", 
  price: 59.99,
  discount: 15,
  discount_price: 44.99,
  image_url: "https://www.nintendo.com/eu/media/images/10_share_images/games_15/nintendo_switch_4/2x1_NSwitch_SuperMarioRPG_image1600w.jpg",
  video_url: "https://youtu.be/RVxb1QhOiVQ",
  platform: "Nintendo",
},
{
  id: 49,
  title: "NBA 2K24",
  sub_title: "NBA 2K24",
  genre: "Sport",
  rating: "PEGI 3",
  developer: "EA",
  description:"Schiera la tua squadra per vivere il passato, il presente e il futuro della cultura del basket con NBA 2K24. Goditi il massimo dell'azione e del realismo oltre alle illimitate opzioni personalizzabili della modalità Il mio GIOCATORE in La mia CARRIERA. Arricchisci la tua collezione con una straordinaria selezione di leggende e crea la formazione dei tuoi sogni in MyTEAM. Scopri una dinamica di gioco più reattiva e grafiche più rifinite giocando con le tue squadre NBA e WNBA preferite in GIOCA ORA.", 
  price: 79.99,
  discount: 60,
  discount_price: 19.99,
  image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReZyXRobOjYJ0-oFpkw56IWKDGo0CacK84hSCfflB0ow&s",
  video_url: "https://youtu.be/OJS1BVniz5c",
  platform: "XBOX",
},
{
  id: 50,
  title: "ARK",
  sub_title: "ARK: Survival Evolved",
  genre: "Action",
  rating: "PEGI 16",
  developer: "Studio Wildcard",
  description:"Rinasci in una nuova esperienza di sopravvivenza dei dinosauri oltre i tuoi sogni più sfrenati... mentre ARK viene reinventato da zero nella tecnologia dei videogiochi di prossima generazione con Unreal Engine 5! Ti svegli su un'isola misteriosa, i tuoi sensi sono sopraffatti dalla luce solare accecante e dai colori brillanti che rimbalzano su ogni superficie intorno a te, le acque azzurre di un'isola verdeggiante lambiscono i tuoi piedi nudi. Un profondo ruggito echeggia dalla giungla nebbiosa, spingendoti all'azione e tu ti alzi, non spaventato, ma incuriosito. Sei pronto a formare una tribù, domare e allevare centinaia di specie di dinosauri e altre creature primordiali, esplorare, creare, costruire e combattere per raggiungere la cima della catena alimentare? Il tuo nuovo mondo ti aspetta... attraversa lo specchio e unisciti ad esso!", 
  price: 49.99,
  discount: 10,
  discount_price: 39.99,
  image_url: "https://i.ytimg.com/vi/0gLODoXanog/maxresdefault.jpg",
  video_url: "https://youtu.be/sYi6iy07GsE",
  platform: "XBOX",
},
{
  id: 51,
  title: "Palword",
  sub_title: "Palword",
  genre: "FPS",
  rating: "PEGI 12",
  developer: "Pocket Pair",
  description:"La mancanza di cibo, un ambiente ostile e le attività illecite dei bracconieri... Questo è un mondo colmo di pericoli. Per sopravvivere, non potrai concederti scrupoli. Potresti persino ridurti a mangiare il tuo Pal...", 
  price: 27.99,
  discount: 0,
  discount_price: 27.99,
  image_url: "https://cdn.akamai.steamstatic.com/steam/apps/1623730/capsule_616x353.jpg?t=1707904340",
  video_url: "https://youtu.be/D9w97KSEAOo",
  platform: "XBOX",
},
{
  id: 52,
  title: "Grand Theft Auto",
  sub_title: "Grand Theft Auto V: Premium Edition",
  genre: "Action",
  rating: "PEGI 18",
  developer: "Rockstar Games",
  description:"Un giovane truffatore, un rapinatore di banche in pensione e uno spaventoso psicopatico si ritrovano nel mirino degli elementi più discutibili del mondo del crimine, del governo statunitense e dell'industria dello spettacolo. Per sopravvivere dovranno mettere in atto una serie di audaci colpi, in una città spietata dove non possono fidarsi di nessuno, men che meno gli uni degli altri.", 
  price: 39.99,
  discount: 22,
  discount_price: 17.99,
  image_url: "https://gaming-cdn.com/images/products/4211/616x353/grand-theft-auto-v-premium-online-edition-premium-online-edition-pc-game-rockstar-cover.jpg?v=1701763976",
  video_url: "https://youtu.be/QkkoHAzjnUs",
  platform: "XBOX",
},
{
  id: 53,
  title: "Evil West",
  sub_title: "Evil West",
  genre: "FPS",
  rating: "PEGI 18",
  developer: "Focus Enterteinment",
  description:"Una minaccia oscura incombe sulla frontiera americana. Nei panni di uno degli ultimi agenti di un'organizzazione segreta dedita all'eliminazione dei vampiri, sei l’ultima linea tra l’umanità e un terrore ancestrale che sta emergendo dalle tenebre. Diventa un supereroe del Far West, elimina la minaccia dei vampiri e salva gli Stati Uniti!", 
  price: 69.99,
  discount: 42,
  discount_price: 27.99,
  image_url: "https://gaming-cdn.com/images/products/12322/616x353/evil-west-pc-gioco-steam-cover.jpg?v=1703153208",
  video_url: "https://youtu.be/5ERcyYnqU9M",
  platform: "XBOX",
},
{
  id: 54,
  title: "Dead Island",
  sub_title: "Dead Island 2",
  genre: "RPG",
  rating: "PEGI 18",
  developer: "Deep Silver",
  description:"Dead Island 2 è un RPG di azione in prima persona, elegante, vibrante e travolto dall'infezione zombi. Esplora una Los Angeles intrisa di sangue. Incontra personaggi fuori dall'ordinario. Uccidi innumerevoli nemici con dettagli squisitamente cruenti. E fai evolvere il tuo personaggio per diventare l'ammazzazombi ideale!", 
  price: 59.99,
  discount: 5,
  discount_price: 54.99,
  image_url: "https://cdn1.epicgames.com/offer/236c74b4cd2e4e3099cbe2ebdc9686fd/EGS_DeadIsland2_DeepSilverDambusterStudios_S1_2560x1440-fdc688ce46680914ee3c4a7949ce8a67",
  video_url: "https://youtu.be/AWFaj4IQ4ro",
  platform: "XBOX",
},
{
  id: 55,
  title: "Botany Manor",
  sub_title: "Botany Manor",
  genre: "Simulation",
  rating: "PEGI 3",
  developer: "Whitethorn Games",
  description:"Ti diamo il benvenuto a Botany Manor, una dimora signorile dell'Inghilterra del XIX secolo. Interpreterai il ruolo di Arabella Greene, una botanica in pensione. Esplora la tua casa e i tuoi giardini, indaga in ogni angolo e trova l'habitat ideale per numerosi esemplari di flora dimenticata. Coltiva ogni pianta per scoprire le qualità misteriose che nasconde...", 
  price: 24.99,
  discount: 0,
  discount_price: 24.99,
  image_url: "https://cdn.akamai.steamstatic.com/steam/apps/1425350/header.jpg?t=1712671134",
  video_url: "https://youtu.be/jrVh3Aubxdo",
  platform: "XBOX",
},
{
  id: 56,
  title: "The last of us",
  sub_title: "The last of us parte II: remastered",
  genre: "Action",
  rating: "PEGI 18",
  developer: "Naughty Dog",
  description:"Rivivi o gioca per la prima volta la storia di Ellie e Abby con miglioramenti grafici, nuove modalità di gioco (come l'esperienza di sopravvivenza roguelike Senza ritorno), l'integrazione del controller wireless DualSense e altro ancora.", 
  price: 69.99,
  discount: 10,
  discount_price: 59.99,
  image_url: "https://image.api.playstation.com/vulcan/ap/rnd/202312/0117/da083fa5e19458dd750aa8a6ea30ba10bac6f87074693df5.jpg",
  video_url: "https://youtu.be/Ye3st9z6jQY",
  platform: "Playstation",
},
{
  id: 57,
  title: "Marvel's Spiderman",
  sub_title: "Marvel's Spiderman 2",
  genre: "Action",
  rating: "PEGI 16",
  developer: "Sony Interactive Enterteinment",
  description:"Oscilla, salta e utilizza le Web Wings per viaggiare nella New York della Marvel, passando rapidamente da Peter Parker a Miles Morales per vivere storie diverse e usare nuovi poteri epici, mentre l'iconico cattivo Venom minaccia di distruggere le loro vite, la loro città e le persone che amano.", 
  price: 59.99,
  discount: 30,
  discount_price: 29.99,
  image_url: "https://image.api.playstation.com/vulcan/ap/rnd/202306/1219/e66c4ae18c5d8e3986a24599b293162a6f5c9eba22968d2c.jpg",
  video_url: "ttps://youtu.be/HuWr23tZ_tws",
  platform: "Playstation",
},
{
  id: 58,
  title: "Returnal",
  sub_title: "Returnal",
  genre: "Action",
  rating: "PEGI 16",
  developer: "Sony",
  description:"Dopo un atterraggio d'emergenza su un pianeta alieno in continuo mutamento, Selene deve cercare la sua via di fuga esplorando le rovine di un'antica civiltà. Isolata e sola, si ritrova a combattere con le unghie e con i denti per la propria sopravvivenza, e ad ogni sconfitta è costretta a rivivere dal principio la sua avventura, intrappolata in un loop apparentemente infinito.", 
  price: 79.99,
  discount: 50,
  discount_price: 29.99,
  image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSw7XxUPnC_yv2V7gomHi-u3nhwVYuwzsckymxF2z_A8A&sg",
  video_url: "https://youtu.be/ov4fJmGCsZM",
  platform: "Playstation",
},
{
  id: 59,
  title: "Death Strandind",
  sub_title: "Death Stranding: Director's cut",
  genre: "Adventure",
  rating: "PEGI 16",
  developer: "Sony",
  description:"Dopo un atterraggio d'emergenza su un pianeta alieno in continuo mutamento, Selene deve cercare la sua via di fuga esplorando le rovine di un'antica civiltà. Isolata e sola, si ritrova a combattere con le unghie e con i denti per la propria sopravvivenza, e ad ogni sconfitta è costretta a rivivere dal principio la sua avventura, intrappolata in un loop apparentemente infinito.", 
  price: 79.99,
  discount: 50,
  discount_price: 29.99,
  image_url: "https://image.api.playstation.com/vulcan/ap/rnd/202106/2214/oP26q4BVa6RJk2CnJllYms2q.jpg",
  video_url: "https://youtu.be/H2Hy96sOnq8",
  platform: "Playstation",
},
{
  id: 60,
  title: "Demon's Souls",
  sub_title: "Demon's Souls",
  genre: "RPG",
  rating: "PEGI 18",
  developer: "Bluepoint Game",
  description:"Da PlayStation Studios e Bluepoint Games arriva il remake di un classico di PlayStation, Demon's Souls. Interamente ricostruito da zero e magnificamente migliorato, questo remake presenta gli orrori di una terra di fantasia oscura e schiacciata dalla nebbia, a una nuova generazione di giocatori. Coloro che hanno già affrontato le sue sfide e le sue avversità potranno nuovamente misurarsi contro l'oscurità con una qualità visiva magnifica e godendo di prestazioni incredibili.", 
  price: 79.99,
  discount: 40,
  discount_price: 39.99,
  image_url: "https://gmedia.playstation.com/is/image/SIEPDC/demons-souls-listing-thumb-01-en-02oct20?$facebook$",
  video_url: "https://youtu.be/2TMs2E6cms4",
  platform: "Playstation",
},
{
  id: 61,
  title: "Sackboy",
  sub_title: "Sackboy: Una Grande Avventura",
  genre: "RPG",
  rating: "PEGI 3",
  developer: "Sony",
  description:"Sackboy, l'iconico eroe dell'universo PlayStation®, torna a vivere avventure mozzafiato in un gigantesco, appassionante e frenetico platform 3D multigiocatore... con nuove e pupazzose abilità!", 
  price: 49.99,
  discount: 40,
  discount_price: 9.99,
  image_url: "https://sm.ign.com/ign_it/screenshot/default/ca_htsh.jpg",
  video_url: "https://youtu.be/6g6XHFinLKM",
  platform: "Playstation",
},
{
  id: 62,
  title: "Destruction AllStars",
  sub_title: "Destruction AllStars",
  genre: "Racing",
  rating: "PEGI 7",
  developer: "Sony",
  description:"Sedici AllStar di grande successo hanno i motori caldi e sono pronti a competere nel nome dell'intrattenimento e della demolizione. Allaccia la cintura e preparati per intensi, esplosivi e imprevedibili livelli di azione a ruota libera, e lotta per vincere il titolo di Campione della Federazione Globale della Distruzione.", 
  price: 39.99,
  discount: 20,
  discount_price: 19.99,
  image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAYvGwcaBxDTPgwQnUMS-rMc0irNtBJ6ZGbPAOTtm62A&s",
  video_url: "https://youtu.be/nNO1k5NCDOk",
  platform: "Playstation",
},
{
  id: 63,
  title: "Gran Turismo",
  sub_title: "Gran Turismo 7",
  genre: "Racing",
  rating: "PEGI 3",
  developer: "Sony",
  description:"Grazie al ritorno della leggendaria modalità GT Simulation, acquista, metti a punto e gareggia nel corso dell'appagante campagna per giocatore singolo man mano che sblocchi nuove auto e sfide. Se ami la competizione diretta, affina le tue abilità e gareggia nella modalità Sport.", 
  price: 79.99,
  discount: 50,
  discount_price: 29.99,
  image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAYvGwcaBxDTPgwQnUMS-rMc0irNtBJ6ZGbPAOTtm62A&s",
  video_url: "https://youtu.be/nNO1k5NCDOk",
  platform: "Playstation",
},

{
  id: 64,
  title: "Super Mario Bros: Wonder",
  sub_title: "Super Mario Bros: Wonder",
  genre: "Adventure",
  rating: "PEGI 3",
  developer: "Nintendo",
  description:"Parti con Mario e i suoi amici per una nuova avventura a scorrimento orizzontale in 2D dove sorprese e meraviglie ti attendono a ogni angolo: Super Mario Bros. Wonder per Nintendo Switch!", 
  price: 39.99,
  discount: 15,
  discount_price: 24.99,
  image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSy3Xs2cIAmv8Yy7EQVrbEe9qEN_yLb32mN-0nKSlkpQ&s",
  video_url: "https://youtu.be/87ZXFw2WA4U",
  platform: "Nintendo",
},
{
  id: 65,
  title: "WarioWare: MoveIt!",
  sub_title: "WarioWare: MoveIt!",
  genre: "Action",
  rating: "PEGI 3",
  developer: "Nintendo",
  description:"Ti attende una miriade di minigiochi basati sul movimento. Ognuno di loro dura solo pochi secondi. Taglia il bambù, fiondati sui pesci, deponi un uovo e molto altro... Pensa in fretta e agisci ancora più rapidamente per superare tutte le sfide!", 
  price: 39.99,
  discount: 20,
  discount_price: 19.99,
  image_url: "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/2x1_NSwitch_WarioWareMoveIt_image1600w.jpg",
  video_url: "https://youtu.be/Ja0SphuczOk",
  platform: "Nintendo",
},
{
  id: 66,
  title: "Snufkin: Melody of Moominvalley",
  sub_title: "Snufkin: Melody of Moominvalley",
  genre: "Adventure",
  rating: "PEGI 3",
  developer: "Nintendo",
  description:"Snufkin: Melody of Moominvalley è un gioco d'avventura musicale dalla ricca trama in cui Tabacco riporta l'armonia nella valle e aiuta i bizzarri e memorabili personaggi e le creature che la abitano. Nella Valle dei Mumin sono sorti uno dopo l'altro orribili parchi che hanno sconvolto il paesaggio e la sua natura armoniosa. Nei panni di Tabacco dovrai distrarre gli agenti di polizia, togliere cartelli e far cadere statue mentre cerchi con tutte le tue forze di ripristinare la natura e la casa degli abitanti della valle, e di porre fine ai piani dell'operoso Guardiano del Parco...", 
  price: 29.99,
  discount: 20,
  discount_price: 9.99,
  image_url: "https://www.nintendo.com/eu/media/images/10_share_images/games_15/nintendo_switch_download_software_1/2x1_NSwitchDS_SnufkinMelodyfOfMoominvalley_GBen_image1600w.jpg",
  video_url: "https://youtu.be/l9MxY7tMMcY",
  platform: "Nintendo",
},
{
  id: 67,
  title: "Tomb Raider",
  sub_title: "Tomb Raider I , II , III Remastered",
  genre: "Adventure",
  rating: "PEGI 16",
  developer: "Aspyr",
  description:"Gioca ai primi tre capitoli originali di Tomb Raider: Per la prima volta in assoluto, vivi l'esperienza completa su piattaforme moderne con questa collezione definitiva contenente tutte le espansioni ed i livelli segreti.", 
  price: 29.99,
  discount: 20,
  discount_price: 9.99,
  image_url: "https://www.nintendo.com/eu/media/images/10_share_images/games_15/nintendo_switch_download_software_1/2x1_NSwitchDS_TombRaider13Remastered_image1600w.jpg",
  video_url: "https://youtu.be/Gm5TlIxTUHw",
  platform: "Nintendo",
},
{
  id: 68,
  title: "Pokémon Spada",
  sub_title: "Pokémon Spada",
  genre: "RPG",
  rating: "PEGI 3",
  developer: "GAME FREAK",
  description:"Preparati a scoprire Galar, un'ampia regione in cui troverai ecosistemi completamente diversi fra loro: campagne tranquille e città moderne, foreste impenetrabili e montagne innevate! In questa regione, abitanti e Pokémon collaborano strettamente per sviluppare le industrie locali.", 
  price: 59.99,
  discount: 20,
  discount_price: 39.99,
  image_url: "https://www.nintendo.com/eu/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_PokemonSword_itIT_image1600w.jpg",
  video_url: "https://youtu.be/fKiz265SMME",
  platform: "Nintendo",
},
{
  id: 69,
  title: "Pokémon",
  sub_title: "Pokémon:Let's go Evee",
  genre: "RPG",
  rating: "PEGI 3",
  developer: "GAME FREAK",
  description:"Attraversa la regione di Kanto e vivi un'emozionante avventura con Pokémon: Let's Go, Pikachu! e Pokémon: Let's Go, Eevee! per Nintendo Switch. Inizierai il tuo viaggio nei panni di un allenatore inesperto, ma potrai farti le ossa strada facendo, catturando, combattendo e facendoti amici numerosi Pokémon!", 
  price: 59.99,
  discount: 20,
  discount_price: 39.99,
  image_url: "https://www.nintendo.com/eu/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_PokemonLetsGoEevee_enGB_image1600w.jpg",
  video_url: "https://youtu.be/9jRtpMKLsts",
  platform: "Nintendo",
},
{
  id: 70,
  title: "Baldur's Gate",
  sub_title: "Baldur's Gate 3",
  genre: "RPG",
  rating: "PEGI 18",
  developer: "Larian Studios",
  description:"Rapito, infettato, perduto. Ti stai trasformando in un mostro, ma mentre la corruzione dentro di te cresce, così fa anche il tuo potere. Forgia una storia di amicizia e tradimento, di sacrificio e sopravvivenza… e del fascino del potere assoluto. Coinvolti in un conflitto tra diavoli, divinità e sinistre forze ultraterrene, tu e il tuo gruppo determinerete il destino dei Forgotten Realms.", 
  price: 69.99,
  discount: 7,
  discount_price: 62.99,
  image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXFsggmWUFsXeS1X8SfJB5B9npn-CbO6hvMI-ed7S95Q&s",
  video_url: "https://youtu.be/05cFrsxtbL0",
  platform: "XBOX",
},
{
  id: 71,
  title: "Suicide Squad",
  sub_title: "Suicide Squad: Kill the Justice",
  genre: "Action",
  rating: "PEGI 18",
  developer: "Warner Bros Games",
  description:"Dai creatori di Batman Arkham, Rocksteady Studios, Suicide Squad: Kill the Justice League è uno sparatutto in terza persona dove la banda di criminali definitiva deve compiere l’impossibile per salvare il mondo: uccidere la Justice League.", 
  price: 69.99,
  discount: 35,
  discount_price: 34.99,
  image_url: "https://cdn.cloudflare.steamstatic.com/steam/apps/315210/header.jpg?t=1707761424",
  video_url: "https://youtu.be/3QHZxzTPsco",
  platform: "XBOX",
},
{
  id: 72,
  title: "Mortal Kombat",
  sub_title: "Mortal Kombat 1",
  genre: "Fighting",
  rating: "PEGI 18",
  developer: "Warner Bros Games",
  description:"Scopri un universo di Mortal Kombat™del tutto rivoluzionato, creato dal Dio del fuoco Liu Kang. Mortal Kombat™ 1 inaugura una nuova era per l'iconico franchise: un nuovo sistema di kombattimento, nuove modalità e Fatality inedite!", 
  price: 69.99,
  discount: 35,
  discount_price: 34.99,
  image_url: "https://cdn.akamai.steamstatic.com/steam/apps/1971870/capsule_616x353.jpg?t=1709136014",
  video_url: "https://youtu.be/UZ6eFEjFfJ0",
  platform: "XBOX",
},
{
  id: 73,
  title: "The Elder Scrolls",
  sub_title: "The Elder Scrolls",
  genre: "RPG",
  rating: "PEGI 18",
  developer: "Bethesda",
  description:"Scopri un universo di Mortal Kombat™del tutto rivoluzionato, creato dal Dio del fuoco Liu Kang. Mortal Kombat™ 1 inaugura una nuova era per l'iconico franchise: un nuovo sistema di kombattimento, nuove modalità e Fatality inedite!", 
  price: 19.99,
  discount: 15,
  discount_price: 4.99,
  image_url: "https://cdn.akamai.steamstatic.com/steam/apps/306130/capsule_616x353.jpg?t=1712247229",
  video_url: "https://youtu.be/XaI-EOVpDvo",
  platform: "XBOX",
},
{
  id: 74,
  title: "The Elder Scrolls",
  sub_title: "The Elder Scrolls",
  genre: "RPG",
  rating: "PEGI 18",
  developer: "Bethesda",
  description:"Scopri un universo di Mortal Kombat™del tutto rivoluzionato, creato dal Dio del fuoco Liu Kang. Mortal Kombat™ 1 inaugura una nuova era per l'iconico franchise: un nuovo sistema di kombattimento, nuove modalità e Fatality inedite!", 
  price: 19.99,
  discount: 15,
  discount_price: 4.99,
  image_url: "https://cdn.akamai.steamstatic.com/steam/apps/306130/capsule_616x353.jpg?t=1712247229",
  video_url: "https://youtu.be/XaI-EOVpDvo",
  platform: "PC",
},
{
  id: 75,
  title: "Dragon Ball Z",
  sub_title: "Dragon Ball Z: Kakarot",
  genre: "Action",
  rating: "PEGI 12",
  developer: "Bandai Namco",
  description: "Ripercorri la storia di Goku e dei guerrieri Z in DRAGON BALL Z: KAKAROT! Oltre rivivere battaglie memorabili, potrai esplorare il mondo di DRAGON BALL Z cacciando, pescando, mangiando e allenandoti con Goku, Gohan, Vegeta e gli altri.", 
  price: 24.99,
  discount: 10,
  discount_price: 14.99,
  image_url: "https://image.api.playstation.com/vulcan/ap/rnd/202212/1616/ebKSYAneFeVLHD7SAWP1l5TE.png",
  video_url: "https://youtu.be/sixbriRUz9M",
  platform: "PC",
},
{
  id: 76,
  title: "It takes two",
  sub_title: "It takes two",
  genre: "Indie",
  rating: "PEGI 3",
  developer: "Electronic Arts",
  description: "Parti per la più folle avventura della tua vita con It Takes Two, un'avventura platform che rivoluziona il genere, creata appositamente per il co-op. Invita un amico a giocare gratis con il Pass amici*, collaborate per superare numerose sfide incredibili con un gameplay fuori dagli schemi. Gioca nei panni di Cody e May, una coppia ai ferri corti, due esseri umani che un incantesimo ha trasformato in bambole. Insieme, intrappolati in un mondo fantastico in cui gli imprevisti si celano dietro ogni angolo, dovranno superare ogni sfida per salvare la propria relazione in pericolo.", 
  price: 19.99,
  discount: 15,
  discount_price: 4.99,
  image_url: "https://image.api.playstation.com/vulcan/ap/rnd/202012/0815/7CRynuLSAb0vysSC4TmZy5e4.png",
  video_url: "https://youtu.be/GAWHzGNcTEw",
  platform: "PC",
},
{
  id: 77,
  title: "Medieval Dinasty",
  sub_title: "Medieval Dinasty",
  genre: "FPS",
  rating: "PEGI 16",
  developer: "Render Cube",
  description: "Trova un terreno su cui costruire la tua dimora. Inizierai da semplice agricoltore o cacciatore, ma man mano che acquisirai più esperienza, apprenderai nuove abilità e le affinerai, diventerai il capo di una fiorente cittadina. Progetta, costruisci e migliora la tua casa: trasforma una semplice capanna in una vasta fattoria. Convinci le persone a unirsi al tuo villaggio. Trova il vero amore e metti su famiglia per garantire una continuità nella tua dinastia.", 
  price: 23.99,
  discount: 14,
  discount_price: 9.99,
  image_url: "https://image.api.playstation.com/vulcan/ap/rnd/202308/1609/9ef2acb3ed2cda2a894342473bd82fda34e73b3a35f57aef.jpg",
  video_url: "https://youtu.be/0m_XJdDvcf4",
  platform: "PC",
},
{
  id: 78,
  title: "Children Of The Sun",
  sub_title: "Children Of The Sun",
  genre: "Arcade",
  rating: "PEGI 16",
  developer: "Devolver Digital",
  description: "Trova un terreno su cui costruire la tua dimora. Inizierai da semplice agricoltore o cacciatore, ma man mano che acquisirai più esperienza, apprenderai nuove abilità e le affinerai, diventerai il capo di una fiorente cittadina. Progetta, costruisci e migliora la tua casa: trasforma una semplice capanna in una vasta fattoria. Convinci le persone a unirsi al tuo villaggio. Trova il vero amore e metti su famiglia per garantire una continuità nella tua dinastia.", 
  price: 44.99,
  discount: 30,
  discount_price: 14.99,
  image_url: "https://cdn.cloudflare.steamstatic.com/steam/apps/1309950/hero_capsule.jpg?t=1712679014",
  video_url: "https://youtu.be/AqHQDRqzxlQ",
  platform: "PC",
},
{
  id: 79,
  title: "Forza Horizion",
  sub_title: "Forza Horizon 5",
  genre: "Racing",
  rating: "PEGI 3",
  developer: "Playground Games",
  description: "La tua avventura Horizon definitiva ti aspetta! Esplora vivaci paesaggi open world del Messico in continua evoluzione. Divertimento al volante illimitato con centinaia tra le migliori auto al mondo.", 
  price: 50.99,
  discount: 14,
  discount_price: 36.99,
  image_url: "https://cdn.akamai.steamstatic.com/steam/apps/1551360/capsule_616x353.jpg?t=1706912726",
  video_url: "https://youtu.be/FYH9n37B7Yw",
  platform: "PC",
},
{
  id: 80,
  title: "Assassin's creed",
  sub_title: "Assassin's creed: Ezio's Collection",
  genre: "Adventure",
  rating: "PEGI 18",
  developer: "Ubisoft",
  description:"Scrivi la storia nei panni del Maestro Assassino Ezio Auditore da Firenze in questa magnifica collezione che comprende la modalità per giocatore singolo di Assassin's Creed 2, Assassin's Creed Brotherhood, Assassin's Creed Revelations e tutti i DLC con grafica migliorata. Due brevi film, Assassin's Creed Lineage® e Assassin's Creed Embers™, completano l'esperienza di Ezio.", 
  price: 17.99,
  discount: 10,
  discount_price: 7.99,
  image_url: "https://image.api.playstation.com/cdn/EP0001/CUSA04893_00/Du24dEL6C7seAl3UQobFN5QqewZ6EXU5.png",
  video_url: "https://youtu.be/PrlE5PmeasA",
  platform: "PC",
},
{
  id: 81,
  title: "Balatro",
  sub_title: "Balatro",
  genre: "Indie",
  rating: "PEGI 18",
  developer: "LocalThunk",
  description: "Il roguelike a tema poker. Balatro è un gioco di costruzione di mazzi in cui formi mani di poker illegali, scopri jolly che stravolgono la partita e attivi combo adrenaliniche e stravaganti, provando una soddisfazione ipnotica.", 
  price: 19.99,
  discount: 15,
  discount_price: 4.99,
  image_url: "https://cdn.cloudflare.steamstatic.com/steam/apps/2379780/header.jpg?t=1712664935",
  video_url: "https://youtu.be/3m6bgbFr82Q",
  platform: "PC",
},
{
  id: 82,
  title: "Star Wars",
  sub_title: "Star Wars: Outlaw",
  genre: "In arrivo",
  rating: "PEGI 12",
  developer: "Ubisoft",
  description: "Star Wars Outlaws è un gioco di azione e avventura di prossima uscita ambientato nell'universo di Star Wars sviluppato da Massive Entertainment e pubblicato da Ubisoft su licenza di Lucasfilm Games. Il gioco è ambientato nel periodo tra L'Impero colpisce ancora e Il ritorno dello Jedi.", 
  price: 79.99,
  discount: 10,
  discount_price: 69.99,
  image_url: "https://multiplayer.net-cdn.it/thumbs/images/2023/06/12/star-wars-outlaws-key-art_article-feature_73a536a1_04vqqz1_jpeg_1600x900_crop_q85.jpg",
  video_url: "https://youtu.be/tcdKEy-aJ6o",
  platform: "Playstation",
},
{
  id: 83,
  title: "No rest for the wicked",
  sub_title: "No rest for the wicked",
  genre: "In arrivo",
  rating: "PEGI 12",
  developer: "Moon Studios",
  description: "No Rest for the Wicked è un videogioco di ruolo d'azione di prossima uscita sviluppato da Moon Studios e pubblicato da Private Division. Ambientato nell'anno 841, il giocatore assume il controllo di un sacro guerriero che deve recarsi sull'isola di Isola Sacra per indagare su una piaga chiamata 'Pestilenza'.", 
  price: 59.99,
  discount: 10,
  discount_price: 49.99,
  image_url: "https://cdn.cloudflare.steamstatic.com/steam/apps/1371980/header.jpg?t=1713196618",
  video_url: "https://cdn.cloudflare.steamstatic.com/steam/apps/257016040/movie480_vp9.webm?t=1713186182",
  platform: "PC",
},
{
  id: 84,
  title: "Tales of Kenzera",
  sub_title: "Tales of Kenzera",
  genre: "In arrivo",
  rating: "PEGI 7",
  developer: "Surgent Studio",
  description: "Tales of Kenzera: ZAU è un videogioco Metroidvania di prossima uscita sviluppato da Surgent Studios e pubblicato da Electronic Arts sotto la sua etichetta EA Originals. Il gioco sarà rilasciato per PC Windows, Nintendo Switch, PlayStation 5 e Xbox Series X e Series S nell'aprile 2024.", 
  price: 59.99,
  discount: 10,
  discount_price: 49.99,
  image_url: "https://media.contentapi.ea.com/content/dam/ea/tales-of-kenzera/zau/common/olorun-fpo-feat-img.png.adapt.crop16x9.1023w.png",
  video_url: "https://youtu.be/5lEbG0Bx83U",
  platform: "Nintendo",
},
{
  id: 85,
  title: "Stellar Blade",
  sub_title: "Stellar Blade",
  genre: "In arrivo",
  rating: "PEGI 16",
  developer: "Sony",
  description: "Stellar Blade è un videogioco action RPG e d'avventura sviluppato da Shift Up e distribuito dalla Sony Interactive Entertainment. L'uscita del gioco è programmata per il 26 aprile 2024, come esclusiva per PlayStation 5.", 
  price: 79.99,
  discount: 10,
  discount_price: 69.99,
  image_url: "https://image.api.playstation.com/vulcan/ap/rnd/202401/2211/40e7cfd126a11fe5118310ebce6d9b3a23e7cabaca717217.png",
  video_url: "https://youtu.be/iSeHgk0RO4M",
  platform: "Playstation",
},
{
  id: 86,
  title: "Homeworld",
  sub_title: "Homeworld 3",
  genre: "In arrivo",
  rating: "PEGI 12",
  developer: "Sony",
  description: "Homeworld 3 è un videogioco di strategia in tempo reale di prossima uscita sviluppato da Blackbird Interactive e pubblicato da Gearbox Software. L'uscita del gioco è prevista per il 13 maggio 2024.", 
  price: 79.99,
  discount: 10,
  discount_price: 69.99,
  image_url: "https://cdn1.epicgames.com/offer/ef7baa6ce017413ab33e7f7e3f466a96/EGS_Homeworld3_BlackbirdInteractive_S1_2560x1440-983f993cb4a722947ee3f404ded3ae95",
  video_url: "https://youtu.be/uGXP7oSeoW0",
  platform: "Playstation",
},
{
  id: 87,
  title: "Sand Land",
  sub_title: "Sand Land",
  genre: "In arrivo",
  rating: "PEGI 12",
  developer: "Bandai Namco",
  description: "Stellar Blade è un videogioco action RPG e d'avventura sviluppato da Shift Up e distribuito dalla Sony Interactive Entertainment. L'uscita del gioco è programmata per il 26 aprile 2024, come esclusiva per PlayStation 5.", 
  price: 79.99,
  discount: 10,
  discount_price: 69.99,
  image_url: "https://nerdmovieproductions.it/wp-content/uploads/2023/06/FyEzEGPaIAAnKIq.jpg",
  video_url: "https://youtu.be/JbKjqVtthPk",
  platform: "Playstation",
},
{
  id: 88,
  title: "UFC",
  sub_title: "UFC 3",
  genre: "Fighting",
  rating: "PEGI 18",
  developer: "Electronic Arts",
  description: "EA SPORTS™ UFC® 3 revolutionizes authentic fighting movement with Real Player Motion Tech, a new animation technology that delivers the most responsive and authentic athletic motion in sports gaming. Every punch, kick, block, and counter has been recaptured and rebuilt on cutting-edge motion-capture tech to look and feel life-like and responsive, delivering a more competitive fighting experience. In G.O.A.T. Career Mode", 
  price: 49.99,
  discount: 30,
  discount_price: 19.99,
  image_url: "https://gaming-cdn.com/images/products/6818/616x353/ea-sports-ufc-3-xbox-one-xbox-series-x-s-xbox-one-xbox-series-x-s-game-microsoft-store-cover.jpg?v=1704797301",
  video_url: "https://youtu.be/Pgh7dGxVKWw",
  platform: "XBOX",
},
{
  id: 89,
  title: "Injustice",
  sub_title: "Injustice 3",
  genre: "Fighting",
  rating: "PEGI 18",
  developer: "Warner Bros",
  description: "After Brainiac's death, to protect the people of earth, Superman accesses Brainiac's ship and selects various alien warriors from Brainiac's city collection to rebuild the Regime. The world turned all over again into Superman's dictatorship. Leading the legion, Superman tries to expand his territory beyond the Earth and into space. When Supergirl refuses Superman's offer while being confined in a red sun cell, he brings in Batman, who is brainwashed by Superman, and to Supergirl's despair.", 
  price: 49.99,
  discount: 30,
  discount_price: 19.99,
  image_url: "https://gaming-cdn.com/images/products/6852/616x353/injustice-3-pc-game-cover.jpg?v=1707321400",
  video_url: "https://youtu.be/8WS47Ms97HM",
  platform: "XBOX",
},
{
  id: 90,
  title: "Super Smash Bros",
  sub_title: "Super Smash Bros: Ultimate",
  genre: "Fighting",
  rating: "PEGI 3",
  developer: "Nintendo",
  description: "Mondi e personaggi leggendari si incontrano per la sfida definitiva: una nuova entrata nella serie Super Smash Bros. per Nintendo Switch!", 
  price: 59.99,
  discount: 20,
  discount_price: 39.99,
  image_url: "https://gaming-cdn.com/images/products/3000/616x353/super-smash-bros-ultimate-switch-switch-game-nintendo-eshop-europe-cover.jpg?v=1701683289",
  video_url: "https://youtu.be/cjdfqXIM-Ko",
  platform: "Nintendo",
},
{
  id: 91,
  title: "Tekken",
  sub_title: "Tekken 6",
  genre: "Fighting",
  rating: "PEGI 18",
  developer: "Bandai Namco",
  description: "After Brainiac's death, to protect the people of earth, Superman accesses Brainiac's ship and selects various alien warriors from Brainiac's city collection to rebuild the Regime. The world turned all over again into Superman's dictatorship. Leading the legion, Superman tries to expand his territory beyond the Earth and into space. When Supergirl refuses Superman's offer while being confined in a red sun cell, he brings in Batman, who is brainwashed by Superman, and to Supergirl's despair.", 
  price: 14.99,
  discount: 7,
  discount_price: 7.99,
  image_url: "https://gaming-cdn.com/images/products/3111/616x353/tekken-6-xbox-one-xbox-series-x-s-xbox-one-xbox-series-x-s-game-microsoft-store-cover.jpg?v=1651828352",
  video_url: "https://youtu.be/G17sa800cEk",
  platform: "PC",
},
{
  id: 92,
  title: "WWE",
  sub_title: "WWE 2K22",
  genre: "Fighting",
  rating: "PEGI 12",
  developer: "Visual Concept",
  description: "WWE 2K22 è un videogioco di wrestling di Visual Concepts pubblicato in data 8 marzo 2022 da 2K Sports per PlayStation 4, Xbox One, PlayStation 5, Xbox Series X e Microsoft Windows", 
  price: 34.99,
  discount: 20,
  discount_price: 14.99,
  image_url: "https://gaming-cdn.com/img/products/10504/pcover/1920x620/10504.jpg?v=1705662308",
  video_url: "https://youtu.be/WC6lrFviM88",
  platform: "XBOX",
},
{
  id: 93,
  title: "Red dead redemption",
  sub_title: "Red dead Redemption 2",
  genre: "Bestseller", 
  rating: "PEGI 18",
  developer: "Rockstar Games",
  description: "America, 1899. Arthur Morgan e la banda di Van der Linde sono in fuga. Con gli agenti federali e i migliori cacciatori di taglie alle costole, la banda deve rapinare, combattere e rubare per farsi strada e cercare di sopravvivere nel cuore di un'America dura e selvaggia. Una serie di conflitti e divisioni rischiano di mettere a repentaglio l'unità del gruppo, e Arthur si ritrova costretto a scegliere tra i suoi ideali e la lealtà nei confronti della banda che l'ha cresciuto.", 
  price: 29.99,
  discount: 10,
  discount_price: 19.99,
  image_url: "https://image.api.playstation.com/cdn/UP1004/CUSA03041_00/Hpl5MtwQgOVF9vJqlfui6SDB5Jl4oBSq.png",
  video_url: "https://youtu.be/gmA6MrX81z4",
  platform: "Playstation",
},
{
  id: 94,
  title: "Horizion",
  sub_title: "Horizon: Forbidden West",
  genre: "Bestseller",
  rating: "PEGI 16",
  developer: "Guerrilla Games",
  description: "Unisciti ad Aloy nell'esplorazione dell'Ovest Proibito, una pericolosa frontiera che nasconde nuove e misteriose minacce.", 
  price: 36.42,
  discount: 12,
  discount_price: 24.99,
  image_url: "https://image.api.playstation.com/vulcan/ap/rnd/202107/3100/cb7gh5N3DjSRathadczu40S9.png",
  video_url: "https://youtu.be/Lq594XmpPBg",
  platform: "Playstation",
},
{
  id: 95,
  title: "God of War",
  sub_title: "God of War: Ragnarok",
  genre: "Bestseller",
  rating: "PEGI 18",
  developer: "Santa Monica Studio",
  description: "Unisciti a Kratos e Atreus in un viaggio mitico alla ricerca di risposte prima che sopraggiunga il Ragnarök. Insieme, padre e figlio si spingeranno al limite nel corso del loro viaggio in ognuno dei nove regni.", 
  price: 47.99,
  discount: 20,
  discount_price: 27.99,
  image_url: "https://gaming-cdn.com/images/products/9312/616x353/god-of-war-ragnarok-ps5-playstation-5-game-playstation-store-europe-cover.jpg?v=1683626731",
  video_url:"https://youtu.be/ItyO3chi9bo",
  platform: "Playstation",
},
{
  id: 96,
  title: "Final Fantasy ",
  sub_title: "Final Fantasy XIV: Dawntrail",
  genre: "Bestseller",
  rating: "PEGI 12",
  developer: "Square Enix",
  description:"Blue seas, clear skies, and boundless possibilities await in Dawntrail, the newest expansion pack for the critically acclaimed FINAL FANTASY XIV Online! Explore uncharted territories with familiar faces as you discover new tribes, confront formidable threats, and expand your horizons as hope's light dawns once more.", 
  price: 35.99,
  discount: 11,
  discount_price: 24.99,
  image_url: "https://gaming-cdn.com/images/products/15658/616x353/final-fantasy-xiv-dawntrail-early-access-pc-game-europe-cover.jpg?v=1711621232",
  video_url: "https://youtu.be/kgiuQwzB6aU",
  platform: "PC",
},
]


const app = express();
app.use(cors());

app.get('/api/oggetti', (req, res) => {
  res.json(users);
});

app.get('/api/oggetti/:id', (req, res) => {
  const gameId = parseInt(req.params.id);
  const game = users.find(game => game.id === gameId);
  if (game) {
    res.json(game);
  } else {
    res.status(404).json({ error: 'Gioco non trovato' });
  }
});

const port = 5001;

app.listen(port, () => {
  console.log(`Server running on port ${port}`);
});